### ISSUE TITLE
When changing patterns (usually after duplication) with ctrl-right, it could seek position

### ISSUE THREAD

**Issue by michaelsjackson** [JoepVanlier/Hackey-Trackey#43] opened 2018-10-10 13:22 UTC
Typical workflow is
1- build a drum pattern
2- duplicate
2.5- switch to next pattern with ctrl-right
3- modify some area, usually something at the end
4- repeat steps 2, 2.5 and 3 infinitely 

While switching to next pattern, in step 2.5, it would be more fun, meaning non-interrupting sound, if the pattern switching would seek position.

**Comment by JoepVanlier** [comment] 2018-10-10 19:05
Unless something is broken on your end, duplicate already puts you in the next pattern.

The seeking behavior by default doesn't sound that useful to me. By default, the tracker just keeps playing past the end of whatever pattern you were in before (going into the next pattern that you just duplicated and which you are seeing already). If you want to make sure it doesn't go further, hit CTRL + L after duplication. Then it puts loop points around that new pattern.

**Comment by michaelsjackson** [comment] 2018-10-10 22:05
I wrote this, because the loop has a stucking sound after you duplicate and the playhead jumps over, it does not seek perfectly, but anyway, one can live with it.

**Comment by JoepVanlier** [comment] 2021-06-05 15:29
Closed as cannot reproduce.

**Closed by JoepVanlier** 2021-06-05 15:29 UTC
Labels: bug
